### PR TITLE
Stop iDownload being killed after three minutes

### PR DESCRIPTION
**Pull request by alfiecg24**

### CODE REVIEW

**Comment by Ingan121** [comment]
Nice work!
Quick question: do we need this for option 1? Are there any benefits to this?
AutoLauncher only opens FSUntetherGUI on boot and that's all, it doesn't need to stay alive.
Maybe making it stay alive could make we don't need to worry about the random restart? ([uptime check](https://github.com/Ingan121/FSUntether/blob/f0f1499785eeb478324271f232465c4edae85ffd/iDownload/autolauncher.c#L25) already handles this though)

**Comment by alfiecg24** [comment]
> Quick question: do we need this for option 1? Are there any benefits to this?

Yeah, seems that’s the correct solution. I’m not too familiar with option 1 as I don’t have a TrollStore-compatible device to test it with. Hope this new commit is okay.

**Comment by Ingan121** [comment]
Thanks, I'll merge it after checking if it doesn't stop for an hour.

**Comment by Ingan121** [comment]
Confirmed working for an hour. Merged, thanks!

**Pull request merged**
